# Generated by Django 4.1.2 on 2022-10-30 05:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('expiry', models.DateTimeField()),
                ('number_of_participant', models.IntegerField()),
                ('max_participant', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='product_image')),
            ],
        ),
    ]
